### ISSUE TITLE
python parser generation

### ISSUE THREAD

**Issue by aparajita** [tolmasky/language#10]
Boy I would love a python parser to be generated. This would make integration with capp_lint and text editors (TextMate, Sublime Text) much easier.

**Comment by kassens** [comment]
I've translated the parser.js to python. It's just for fun and work in progress and likely still contains bugs. You can feed grammars in json form to it.

https://github.com/kassens/language

**Comment by aparajita** [comment]
Awesome, thank you!

**Comment by kassens** [comment]
On a simple grammar, it works, but there's some bug when I try to parse a JS file with the JS grammar.
