### ISSUE TITLE
Not compatible with Node 0.6?

### ISSUE THREAD

**Issue by mgetz** [tolmasky/language#15]
What is the restriction that makes this not compatible with node version 0.6?

Thanks.
Mark

**Comment by shepherdsam** [comment]
Pull Request #16 Will allow this to be installed using npm with node v0.6

**Comment by mgetz** [comment]
Nice work!

On Thu, Jan 26, 2012 at 1:42 AM, Sam Shepherd
reply@reply.github.com
wrote:

**Comment by mgetz** [comment]
Thanks!
