### ISSUE TITLE
Cut placement

### ISSUE THREAD

**Issue by ghost** [tolmasky/language#4]
The term cut placement is used on the home page and project description but it's unclear what this refers to... there's no Wikipedia entry or link to a specific definition, so I'm opening an issue :)

**Comment by tolmasky** [comment]
What is insufficient about the url that immediately follows the cut reference: http://www.ialab.cs.tsukuba.ac.jp/~mizusima/publications/paste513-mizushima.pdf ?

**Comment by ghost** [comment]
Ok, yeah it's not clear that there would be a reference to "cut" in that document. Having just searched it for "cut placement" (no matches), then "cut" (match found: cut _operator_), I can see the relevance. 

But something like this would definitely be more explicit:

"and support for automatic cut placement is coming to maintain mostly constant space as well (for a discussion of cut operators see: url"
